# This workflow is based on pytest-blender which allows pytest to be used from inside Blender's python while running Blender in headless mode 
# https://github.com/mondeja/pytest-blender   

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        blender-version:
          - '2.93.1'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Cache Blender ${{ matrix.blender-version }}
        uses: actions/cache@v2.1.5
        id: cache-blender
        with:
          path: |
            blender-*
            _blender-executable-path.txt
          key: ${{ runner.os }}-${{ matrix.blender-version }}
      - name: Download Blender ${{ matrix.blender-version }}
        if: steps.cache-blender.outputs.cache-hit != 'true'
        id: download-blender
        run: |
          python -m pip install --upgrade blender-downloader
          echo "$(blender-downloader \
          ${{ matrix.blender-version }} --extract --remove-compressed \
          --quiet --print-blender-executable)" > _blender-executable-path.txt
      - name: Install dependencies
        id: install-dependencies
        run: |
          echo "11111111111111111"
          python -m pip install .[test]
          echo "22222222222222"
          python -m pip install pytest-blender
          echo "25252525"
          blender_executable="$(< _blender-executable-path.txt tr -d '\n')"
          echo "33333"
          python_blender_executable="$(pytest-blender --blender-executable $blender_executable)"
          echo "444444"
          $python_blender_executable -m ensurepip
          echo "555555"
          $python_blender_executable -m pip install pytest
          echo "666666"
          echo "::set-output name=blender-executable::$blender_executable"
          pip install pylint
      - name: Test with pytest
        run: pytest -svv --blender-executable "${{ steps.install-dependencies.outputs.blender-executable }}" tests